service: auth-service

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource: "*"

functions:
  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: post
